#!/usr/bin/env bash

# HOST="http://localhost:3000"
HOST="https://amigo-secreto-u376.onrender.com"
JSONH="Content-Type: application/json"
ID_GRUPO=$(curl -s -X POST $HOST/grupos | jq .id )

curl -s $HOST/grupos/$ID_GRUPO/participantes -H "$JSONH" -d '{"nome": "Fulano123"}'
curl -s $HOST/grupos/$ID_GRUPO/participantes -H "$JSONH" -d '{"nome": "Fulano456"}'
curl -s $HOST/grupos/$ID_GRUPO/participantes -H "$JSONH" -d '{"nome": "Fulano789"}'
curl -s $HOST/grupos/$ID_GRUPO/participantes -H "$JSONH" -d '{"nome": "Fulano12345"}'
curl -s $HOST/grupos/$ID_GRUPO/participantes -H "$JSONH" -d '{"nome": "Fulano67890"}'

curl -s -X POST $HOST/grupos/$ID_GRUPO/sorteios

curl -s $HOST/grupos/$ID_GRUPO/participantes/Fulano123/amigo_secreto
curl -s $HOST/grupos/$ID_GRUPO/participantes/Fulano456/amigo_secreto
curl -s $HOST/grupos/$ID_GRUPO/participantes/Fulano789/amigo_secreto
curl -s $HOST/grupos/$ID_GRUPO/participantes/Fulano12345/amigo_secreto
curl -s $HOST/grupos/$ID_GRUPO/participantes/Fulano67890/amigo_secreto